stages:
  - deploy

deploy_stack:
  stage: deploy
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker stack deploy --compose-file docker-compose.yml upost
  environment:
    name: production
  only:
    - master