version: "3.7"

x-logging: &loki-logging
  driver: json-file
  options:
    tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

services:
  loki:
    image: grafana/loki:2.2.1
    ports:
      - "3100"
    volumes:
      - ./config/loki/loki-config.yaml:/mnt/config/loki-config.yaml
    command: -config.file=/mnt/config/loki-config.yaml
    networks:
      - loki
    logging: *loki-logging

  promtail:
    image: grafana/promtail:2.2.1
    volumes:
      - ./config/loki/promtail-config.yaml:/mnt/config/promtail-config.yaml
      - /var/lib/docker/containers:/host/containers
    command: -config.file /mnt/config/promtail-config.yaml
    networks:
      - loki
    logging: *loki-logging

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./config/grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      - loki
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 1234
    logging: *loki-logging

  backend:
    image: gitlab.mollys.uz:5050/upost/backend/upost-backend:main
    ports:
      - "4000:4000"
    logging: *loki-logging
    networks:
     - redis
    depends_on:
     - redis

  frontend:
    image: gitlab.mollys.uz:5050/upost/frontend/main-frontend:master
    ports:
      - "5000:80"
    logging: *loki-logging

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks:
      -  redis
    logging: *loki-logging

volumes:
  grafana-data:
  upost-backend:
  redis:

networks:
  grafana:
  frontend:
  redis:
  upost:
  loki:
