version: "3.7"

x-logging: &loki-logging
  driver: json-file
  options:
    tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

services:
  backend:
    image: gitlab.mollys.uz:5050/upost/backend/upost-backend:{IMAGE_TAG}
    ports:
      - "4000:4000"
    logging: *loki-logging
    networks:
     - redis
    depends_on:
     - redis

  frontend:
    image: gitlab.mollys.uz:5050/upost/frontend/main-frontend:${IMAGE_TAG}
    ports:
      - "5000:80"
    logging: *loki-logging

volumes:
  grafana-data:
  upost-backend:
  redis:

networks:
  grafana:
  frontend:
  redis:
  upost:
  loki:
